Fixing #37, #52, #53, #54, #55
wso2-dev-ux/theme-wso2 pull request #56
Opened 2017-07-19 10:08 UTC by erangatl

2017-07-20 05:39 UTC, thusithak requested changes

2017-07-20 05:39 UTC, thusithak commented on docs/demo/general-form-elements.html
> -            <input type="text" class="form-control" id="exampleInputUsername1" placeholder="Enter Username">
can we refrain from using numerics in ids unless it's being auto generated?

2017-07-20 05:39 UTC, thusithak commented on docs/demo/general-form-elements.html
> +                <button id="btnTransfer" type="submit" class="btn">Transfer cash</button>
use same id naming convention

2017-07-20 05:43 UTC, thusithak requested changes

2017-07-20 05:43 UTC, thusithak commented on docs/demo/buttons.html
> +            <!-- buttons -->
can we affix or suffix some string to uniquely identify "btn-default" id from "btn-default" class, there shouldnt be an ambiguity.

2017-07-20 06:00 UTC, erangatl commented on docs/demo/general-form-elements.html
> +                <button id="btnTransfer" type="submit" class="btn">Transfer cash</button>
Fixed

2017-07-20 06:00 UTC, erangatl commented on docs/demo/general-form-elements.html
> -            <input type="text" class="form-control" id="exampleInputUsername1" placeholder="Enter Username">
fixed

2017-07-20 06:27 UTC, erangatl commented on docs/demo/buttons.html
> +            <!-- buttons -->
fixed

2017-07-20 06:31 UTC, thusithak approved these changes

2017-07-25 04:21 UTC, merged

2017-07-25 05:04 UTC, jeradrutnam commented on docs/demo/buttons.html
> +            <button id="btn-default-id" type="button" class="btn btn-default">Default</button>
Why do we have id names ending with "*-id" ? Shall we take it out?

2017-07-25 05:04 UTC, jeradrutnam commented on docs/demo/buttons.html
> +            <a id="btn-group-more" href="http://getbootstrap.com/components/#btn-groups" target="_blank">http://getbootstrap.com/components/#btn-groups</a>
Why do we have "btn-*" prefix for link id, shall we take it out?

2017-07-25 05:04 UTC, jeradrutnam commented on docs/demo/general-form-elements.html
> +                    <input id="sample-text" type="text" class="form-control" value="Some text">
Shall we add a prefix to these IDs? e.g. "form-control-*"

2017-07-25 05:25 UTC, erangatl commented on docs/demo/buttons.html
> +            <button id="btn-default-id" type="button" class="btn btn-default">Default</button>
This is added to a review request to  uniquely identify "btn-default" id from "btn-default" class, 
Let's have a set of standard for naming.

2017-07-25 05:25 UTC, erangatl commented on docs/demo/general-form-elements.html
> +                    <input id="sample-text" type="text" class="form-control" value="Some text">
-1 on having a 13 character prefix for ID field.
Let's have a set of standard for naming.