[Fixed #73] Creating Avatar React Component
wso2-dev-ux/theme-wso2 pull request #74
Opened 2017-11-24 10:27 UTC by srsharon

2017-11-24 11:23 UTC, jeradrutnam requested changes
Please update the files as requested offline.

2017-11-24 11:23 UTC, jeradrutnam commented on module/components/Avatar/Readme.md
> +<Avatar src='https://www.shareicon.net/data/128x128/2016/07/10/119669_people_512x512.png' ></Avatar>
Please change this to a local file

2017-11-25 11:11 UTC, thusithak requested changes

2017-11-25 11:11 UTC, thusithak commented on module/components/Avatar/index.js
>  }
Please add a newline at the end for all files as per [eslint](https://eslint.org/docs/rules/eol-last) and [Airbnb](https://github.com/airbnb/javascript#whitespace--newline-at-end) spec

2017-11-27 09:52 UTC, closed without merging